Repository omarimran2000/Elevator-Simulator, pull requests merged in 2021-02, with the labels that each got.

#14 Fix busy waiting
  src/ElevatorSubsystem/ArrivalSensor.java
  src/ElevatorSubsystem/Elevator.java
  src/FloorSubsystem/Floor.java
  src/FloorSubsystem/FloorSubsystem.java
  src/Main.java
  src/SchedulerSubsystem/Scheduler.java
Labels: bug

#26 Add junit5
  .classpath
  .gitignore
  .project
  test/CSVTest.java
  test/CommunicationTest.java
Labels: testing

#29 state machine
  src/ElevatorSubsystem/ArrivalSensor.java
  src/ElevatorSubsystem/Door.java
  src/ElevatorSubsystem/Elevator.java
  src/ElevatorSubsystem/ElevatorButton.java
  src/ElevatorSubsystem/ElevatorLamp.java
  src/ElevatorSubsystem/Motor.java
  src/FloorSubsystem/DirectionLamp.java
  src/FloorSubsystem/Floor.java
  src/FloorSubsystem/FloorButton.java
  src/FloorSubsystem/FloorLamp.java
  src/FloorSubsystem/FloorSubsystem.java
  src/Main.java
  src/SchedulerSubsystem/Event.java
  src/SchedulerSubsystem/Scheduler.java
  test/CSVTest.java
  test/CommunicationTest.java
Labels: enhancement

#39 Config file
  .gitignore
  resources/config.cfg
  src/ElevatorSubsystem/ArrivalSensor.java
  src/ElevatorSubsystem/Door.java
  src/ElevatorSubsystem/Elevator.java
  src/FloorSubsystem/Floor.java
  src/FloorSubsystem/FloorSubsystem.java
  src/Main.java
  src/util/Config.java
  src/util/package-info.java
  test.csv
Labels: enhancement

#40 Move tests
  test/CSVTest.java
  test/CommunicationTest.java
Labels: bug

#41 Add sleep between events
  src/FloorSubsystem/Floor.java
Labels: bug

#44 Fix Motor
  src/ElevatorSubsystem/Elevator.java
  src/ElevatorSubsystem/Motor.java
Labels: bug

#46 Fix test
  src/ElevatorSubsystem/Elevator.java
  src/ElevatorSubsystem/Motor.java
  test/CSVTest.java
  test/CommunicationTest.java
  test/ElevatorMotorTest.java
  test/StateTest.java
Labels: bug

#51 Fix config
  src/ElevatorSubsystem/ArrivalSensor.java
  src/ElevatorSubsystem/Elevator.java
Labels: bug

#52 Erica/buttons
  src/ElevatorSubsystem/ArrivalSensor.java
  src/ElevatorSubsystem/Door.java
  src/ElevatorSubsystem/Elevator.java
  src/ElevatorSubsystem/ElevatorButton.java
  src/ElevatorSubsystem/ElevatorLamp.java
  src/ElevatorSubsystem/Motor.java
  src/FloorSubsystem/DirectionLamp.java
  src/FloorSubsystem/Floor.java
  src/FloorSubsystem/FloorButton.java
  src/FloorSubsystem/FloorLamp.java
  src/FloorSubsystem/FloorSubsystem.java
  src/Main.java
  src/SchedulerSubsystem/Event.java
  src/SchedulerSubsystem/Scheduler.java
  src/utill/Config.java
  test/CSVTest.java
  test/CommunicationTest.java
  test/ElevatorMotorTest.java
  test/StateTest.java
Labels: enhancement
